### ISSUE TITLE
`helm diff upgrade` doesn't respect the `--allow-unreleased` flag

### ISSUE THREAD

**Issue by andrewnazarov** [databus23/helm-diff#121]
I'm trying to get the diff for my released which has not been released yet.

`helm diff upgrade --allow-unreleased printing chartmuseum/printing --version ~0.1.0 --namespace shared --values printing/values.yaml` returns
```
Error: "printing-beta" has no deployed releases
"printing-beta" has no deployed releases
Error: plugin "diff" exited with error
```
Is this the expected behavior?

**Comment by andrewnazarov** [comment]
helm diff version
2.11.0+3

**Comment by andrewnazarov** [comment]
Oh, boy. This is the same old story with Helm releases not been purged. `helm delete --purge` solves the problem. Any chances to work around this?

**Comment by mumoshu** [comment]
Hrm... I'm unsure how we could improve the situation from the helm-diff perspective.

Automatically running a non-idempotent operation like `helm del --purge` from helm-diff won't be a solution, indeed.

Then, do we need helm-diff to run `helm list | grep FAILED` on a `no deployed releases` error, so that helm-diff could print a mitigation info, like `please helm del --purge therelease` to fix it?

**Comment by andrewnazarov** [comment]
I haven't come up with anything reasonable either. But you know in some cases there won't be the FAILED state. 

I like how `helm diff` handles the absence of installed release. But in our case even if you make it show the message to a user and print a nice diff, that user won't be able to successfully run `helm install` afterward due to this annoying Helm behavior.

Probably it looks like tilting at windmills.
