### ISSUE TITLE
Helm 3: diff looks like .Capabilities.APIVersions.Has always false

### ISSUE THREAD

**Issue by jkroepke** [databus23/helm-diff#165]
I have some conditions on my chart for check apis installed on the kubernetes server like
```
{{ if .Capabilities.APIVersions.Has "image.openshift.io/v1" }}
```
While on helm 2 the condition correctly evalutated it looks like on helm 3 the condition is always false.

The reason is the diff output is wrong because all code inside the if is marked as removed.

Using 3.0.0-rc.7 of helm-diff

**Comment by pkalemba** [comment]
+1 
I have the same problem for stable/prometheus-operator and stable/filebeat
Looks like it has problem with CRD only.

**Comment by databus23** [comment]
Yeah, the problem is that `helm template` is not talking to the apiserver, it has the default apis harcoded. It also always reports 1.16. as its version: https://github.com/helm/helm/blob/2f4ef705a9e8ea0e38a2c99c29c5e4de59b03d75/pkg/chartutil/capabilities.go#L30-L37

 This might be solved by using `--validate` which `helm diff` is not using at the moment. Last time I checked `--validate` would fail if resources where already present in the cluster. This might have changed. In general for a more correct diff output we would need `helm template` to have the actual capabilities of the cluster loaded.

**Comment by databus23** [comment]
Yeah, so rendering the chart with `helm template --validate` would give us a correct `.Capabilites` but at the moment this will break because of this: https://github.com/helm/helm/issues/6663

I think we need to create an upstream issue and discuss how this could be solved. I think it would be helpful if helm template could skip the exitingResource check. But it seems this requires some discussions with the maintainers: https://github.com/helm/helm/issues/6663#issuecomment-547526721

As it stands helm-diff can't properly render charts that make use of `.Capabilities` which I would like to fix.

/cc @thomastaylor312

**Comment by thomastaylor312** [comment]
Hey @databus23! Just catching up on things after a bunch of vacation. So is the main problem around not having the proper api versions available in the `.Capabilities`? Is it something beyond using the `--api-versions` flag?

**Comment by jkroepke** [comment]
Instead using `helm template` internally is `helm upgrade --dry-run` a valid option?
