### ISSUE TITLE
helm-diff does not understand lookup or hooks

### ISSUE THREAD

**Issue by jonathanhartley** [databus23/helm-diff#219]
I have some code using the lookup function in helm 3 to not disturb a secret if it exists

`{{ if not (lookup "v1" "Secret" $rns (printf "%s-%s-%s" "mysql" ( .user | replace "_" "-" ) "secret") ) }}`

It creates a random password on install (and if the secret gets deleted) for every user asked for in the chart values

helm diff picks up every time that the password has changed but the lookup returns true so the secret would not be deployed

also it does not understand the concept of hooks

`  annotations:
    "helm.sh/hook": pre-install`

This resource would only be installed "pre-install" i.e. not on an upgrade but diff picks up that the deployment would change which is incorrect

**Comment by semoac** [comment]
Hi.
I stumble with this problem last night and I think is a `helm template` and `helm install --dry-run` problem, not an `helm-diff` problem. https://github.com/helm/helm/issues/8137

Basically, because of security concerns, `helm template` and `helm install --dry-run` must not have access to a live cluster.
