### ISSUE TITLE
Changes in chart values.yaml aren't displayed in diff

### ISSUE THREAD

**Issue by jwenz723** [databus23/helm-diff#248]
I have a helm chart defined [here](https://github.com/jwenz723/gocolor/tree/main/k8s/helm/gocolor) that I am testing with. I have this repository cloned locally. I executed the following steps to evaluate helm-diff:

1. `cd k8s/helm/`
1. since the helm chart has not yet been installed into my k8s cluster I include the --allow-unreleased flag when I generate the diff: `helm diff upgrade --allow-unreleased testgocolor ./gocolor`
1. install the chart to my cluster: `helm upgrade -i testgocolor ./gocolor`
1. make a change to the [gocolorEnv.color](https://github.com/jwenz723/gocolor/blob/6cf0d6128ee78d1f554639e3994b630e3ee829e0/k8s/helm/gocolor/values.yaml#L23) property in the charts values.yaml file (note: I am modifying the values.yaml file contained within the chart root, not a custom values.yaml file that I pass to helm with the --values flag)
1. I try to generate a diff: `helm diff upgrade --allow-unreleased testgocolor ./gocolor`

When the last command is executed I get no output, i.e. no diff is detected. Is this expected behavior?

I have found that a diff is generated if I specify the `--reset-values` flag like: `helm diff upgrade --allow-unreleased --reset-values testgocolor ./gocolor`.

**Comment by mumoshu** [comment]
Came from #250. As I have never realized this issue myself, it sounds like a very nasty bug. Thanks for reporting! Let me check #250

**Comment by jnoordsij** [comment]
I still seem to run into this bug on the latest version, any updates on this issue?

**Comment by mumoshu** [comment]
@jnoordsij From which helmfile version did you start to see your issue?

**Comment by jnoordsij** [comment]
The case mentioned at the start of the issue probably still is displaying an empty diff. I don't have a local setup atm I can use to verify this, as it is very similar to my usecase.

I think the problem is this: https://github.com/databus23/helm-diff/blob/master/cmd/helm3.go#L108
It seems that this behavior might have been present in Helm v2, but never has been in v3. So if you now change values in the `values.yaml` part of your chart, running `helm upgrade <release-name> <chart-dir>` will apply those changes, but using `helm diff` shows an empty diff as it forces the `--reuse-values` flags which then in turn ignores the changes.

**Comment by mumoshu** [comment]
@jnoordsij Thanks a lot for sharing your insight! Just confirming, but does that basically mean helm3 defaults to `--reset-values`?
