### ISSUE TITLE
Helm diff always shows a diff in the caBundle

### ISSUE THREAD

**Issue by lifelofranco** [databus23/helm-diff#254]
I am currently using the [AWS load balancer controller](https://github.com/aws/eks-charts/tree/master/stable/aws-load-balancer-controller) helm chart. Running `diff` always shows a revision in the caBundle.

<img width="1205" alt="Screen Shot 2020-12-11 at 7 11 21 PM" src="https://user-images.githubusercontent.com/4952784/101896912-b0386400-3be4-11eb-9b27-1987feeb0e3a.png">

**Comment by katiekeel** [comment]
I'm also having this issue, except with the `letsencrypt` chart, and the `spec.acme.privateKeySecretRef.name` value. Both strings are exactly the same, but show as a diffed line.

![Screen Shot 2021-01-29 at 12 32 32 PM](https://user-images.githubusercontent.com/11282627/106307991-16795480-622e-11eb-90e1-38a50ca602cd.png)

**Comment by jo2y-tock** [comment]
Note: I'm not a helm diff maintainer, this is a drive by comment because I was looking to debug something else. I probably won't be able to help much more.

Technically, there is a diff in the @lifelofranco's screenshot. It starts in the first line about 2-3 dozen characters in (SURQek vs SURREN).

Looking at the referenced helm chart, a new caBundle value is generated from random data each time you run helm (See [offending line](https://github.com/aws/eks-charts/blob/master/stable/aws-load-balancer-controller/templates/_helpers.tpl#L81) and [genCa](https://helm.sh/docs/chart_template_guide/function_list/#genca) function). So diff is doing the right thing. The problem seems to be more with the chart.

For @katiekeel's screenshot, I'm stumped and I didn't find a letsencrypt chart in a quick search.  Usually when I see something like that happen, it's either a trailing whitespace issue that's being preserved in one place and not the other, or one or more of the letters in one is a look-a-like unicode letter. Ie. visually the same, but byte-wise different.  For this, I use either careful selection with the mouse to see if a hidden space is there, or pipe it to `od -a` to see what I get.

Note the 'sp' in the second one.
```shell
% echo foo | od -a
0000000    f   o   o  nl
0000004 
% echo foo\ | od -a
0000000    f   o   o  sp  nl
0000005
```
