### ISSUE TITLE
"helm plugin install https://github.com/databus23/helm-diff" doesn't work

### ISSUE THREAD

**Issue by GitJakobHub** [databus23/helm-diff#255]
Hi, 
I was trying to install the helm plugin via the command: helm plugin install https://github.com/databus23/helm-diff

I got the following response: 
Error: Unable to retrieve local repo information: exit status 1

A colleague of mine did it a few days ago and he was succesfull. 
Can someone help me? 

Thanks in advance
Jakob

**Comment by aackerman** [comment]
This appears to be caused by the fact that [install-binary.sh](https://github.com/databus23/helm-diff/blob/master/install-binary.sh#L71-L84) makes a request to github that for some requests will return pretty-printed and some request it will return compact JSON and it doesn't handle the compact version properly.

**Comment by aackerman** [comment]
Also `helm home` has been deprecated, so that doesn't work anymore [here](https://github.com/databus23/helm-diff/blob/master/install-binary.sh#L11).

**Comment by rami-foo** [comment]
any fix?

helm plugin add https://github.com/databus23/helm-diff
Error: Unable to retrieve local repo information: exit status 1
