### ISSUE TITLE
helm-diff should just ignore unknown flags or have some switch to ignore them

### ISSUE THREAD

**Issue by red8888** [databus23/helm-diff#278]
This error is a nuisance `Error: unknown flag: --create-namespace`

Its not a huge deal but I think I should be able to pass the same command I pass to "upgrade" to helm-diff. I don't want to have to remember which switches it does and doesn't understand especially because I'm scripting this out. I want to have my helm upgrade command a string and just swap `helm upgrade` with `helm diff`

Maybe there could be a `--ignore-unknown-flags` switch or something?

**Comment by mumoshu** [comment]
@red8888 Hey! Thanks for the suggestion. Just took some time to think about this, but still not sure if that's really the right direction.

Wouldn't setting `--ignore-unknown-flags` hide real errors like you typed a wrong flag like `--valus somefile.yaml`?
How can we differentiate ignorable errors and real errors?

**Comment by mumoshu** [comment]
It turns out @johanfleury has kindly submitted a PR #243 for this before.
But my question still applies.

Can we instead hide the feature behind some envvar, like `HELM_DIFF_IGNORE_UNKNOWN_FLAGS=1 helm diff ...`?
Then I agree this is just a good addition to helm-diff.

**Comment by johanfleury** [comment]
My workflow (and yes, [there’s an XKCD for that](https://xkcd.com/1172/)) is to use the search function of my shell to go back to a previous `helm upgrade` invocation and to add `diff` at the beginning.

Having to set and envvar or a flag will not make it better than the current situation and if it becomes popular to the point that mostly everyone uses it, then there’s no point in having it in the first place.

Another solution would be to match helm flags explicitly but ignore them.

**Comment by mumoshu** [comment]
> Having to set and envvar or a flag will not make it better than the current situation and if it becomes popular to the point that mostly everyone uses it, then there’s no point in having it in the first place.

I don't get this. Forcing this feature does help your use-case a lot, but doesn't help my use-case as I want helm-diff to complain when I passed wrong flags.

Can't you just `export HELM_DIFF_IGNORE_UNKNOWN_FLAGS=1` so that you don't need to set it everytime you run helm-diff? You can even set it in e.g. your bash_profile, so that you can fully opt-in to enable this feature by default, while users like me not affected at all.

**Comment by tsterker** [comment]
Some thoughts:

**1. Opt-in:**
I agree that making this an implicit behavior could lead to confusion/bugs and I like the **opt-in** idea.

**2. Hard-coded:**
But maybe this could still be combined with what @johanfleury said:

> Another solution would be to match helm flags explicitly but ignore them.

IMHO, it would make sense to **explicitly ignore certain options directly in the plugin** (e.g. I think the `timeout` option could be an obvious candidate to ignore?)

**3. Opt-in (explicit):**
An alternative approach (or rather addition?) could be to also allow **explicitly setting options to ignore via environment variable** (e.g. `HELM_DIFF_IGNORE_FLAGS`). This way there would be more fine-grained control instead of the all-or-nothing `HELM_DIFF_IGNORE_UNKNOWN_FLAGS`.

**Comment by mumoshu** [comment]
I like `3. Opt-in (explicit):` the most as it is least invasive and it works on any flags current/future helm has!

**Comment by tsterker** [comment]
@mumoshu Is there any plan to introduce a `HELM_DIFF_IGNORE_FLAGS` flag?

This could really simplify some scripts where I just want to drop a `diff` in front of my helm command for sanity checking/auditing before doing the real thing.

**Comment by mumoshu** [comment]
@tsterker `HELM_DIFF_IGNORE_UNKNOWN_FLAGS` is going to be added via #328

**Comment by tsterker** [comment]
@mumoshu Thank you for the follow-up; greatly appreciated! :)

**Comment by Rapsody09** [comment]
Hello @mumoshu, I am trying to use this ignore flag, but I don't understand why I still get an unknow error flag ... Am I doing something wrong ?

My code running in a gitlab job script, and some variables are added trough the ${ADD_VARIABLES} variable, I cannot control them :

```shell
    - helm plugin install https://github.com/databus23/helm-diff
    - export HELM_DIFF_IGNORE_UNKNOWN_FLAGS="true"
    - printenv | grep HELM_DIFF_IGNORE_UNKNOWN_FLAGS
    - helm diff --context 4 -q upgrade --install ${ADD_VARIABLES} -f Environnement/${FOLDER_APP}/values-${ENV}.yaml ${APP_NAME} ${EXTERNAL_CHART} --version ${EXTERNAL_CHART_VERSION} -n ${NAMESPACE}
```
When running I get an error :

```shell
$ helm plugin install https://github.com/databus23/helm-diff
Downloading https://github.com/databus23/helm-diff/releases/latest/download/helm-diff-linux-amd64.tgz
Preparing to install into /root/.local/share/helm/plugins/helm-diff
Installed plugin: diff
$ export HELM_DIFF_IGNORE_UNKNOWN_FLAGS="true"
$ printenv | grep HELM_DIFF_IGNORE_UNKNOWN_FLAGS
HELM_DIFF_IGNORE_UNKNOWN_FLAGS=true
$ helm diff --context 4 -q upgrade --install ${ADD_VARIABLES} -f Environnement/${FOLDER_APP}/values-${ENV}.yaml ${APP_NAME} ${EXTERNAL_CHART} --version ${EXTERNAL_CHART_VERSION} -n ${NAMESPACE}
Error: unknown flag: --insecure-skip-tls-verify
```

Thanks a lot for your help
