### ISSUE TITLE
Option to ignore specific keys

### ISSUE THREAD

**Issue by timstoop** [databus23/helm-diff#406]
Currently, there's an option to ignore entire resources, but I believe it's not possible to ignore specific keys instead. I'd love to be able to ignore things like `.metadata.labels.helm.sh/chart` and the like, as those are usually the most common and least interesting. Having the option to ignore a preset list of those key by default would make life a lot easier.

**Comment by gfdsa** [comment]
Helmfile user here. We had this this idea of tracking the helmfile runs using a label injected using kustomize into every freshly deployed resource. But being an updated value it triggers helmfile every time for every release event if there was no meaningful update. Helmfile bases its decision on helm-diff, so a way to ignore a label change would allow us to do exactly what we want.

**Comment by yxxhero** [comment]
https://github.com/databus23/helm-diff/pull/475

**Comment by TheMeier** [comment]
Also if the resulting diff is empty it is quite confusing that a header is printed like

```
foo, foo-configmap, ConfigMap (v1) has changed:
```

followed by nothing

**Comment by TheMeier** [comment]
Related https://github.com/databus23/helm-diff/pull/768

**Comment by matmut7** [comment]
Hi, I have roughly the same need as @gfdsa : even when I suppress some diffs with the `--suppress[...]` CLI flags, I can't skip subsequent tool calls because exit code stays the same whether I suppress diffs or not.

Could the solution be some CLI flag like `suppress-before-exitcode` so I can suppress diffs and get the "there are no diffs" exit code ? I feel like ignoring some well-known false-positive diffs is a relevant feature, let me know what you think 😄 I'd be glad to contribute if that's the right direction !
