### ISSUE TITLE
Make helm-diff, helmfile diff work better with namespaces for unreleased charts

### ISSUE THREAD

**Issue by foklepoint** [databus23/helm-diff#66]
Currently when you want to diff a chart via helmfile diff under the following conditions:
- The chart has no previous releases
- There is a namespace specified in helmfile

The diff is inaccurate because `helm upgrade diff --allow-unreleased` hard-codes to [using the default namespace here](https://github.com/databus23/helm-diff/blob/master/cmd/upgrade.go#L112). However, helmfile can actually contain the correct namespace and be other than default. This would require for helm-diff to read in the namespace from the cli, if supplied, and require helmfile to send the the namespace as a flag to helm-diff.

**Comment by jubel-han** [comment]
Also, the can't specify the `--tiller-namespace`, it's barely unable to use without it.

**Comment by mumoshu** [comment]
@foklepoint @jubel-han Thanks for the feedbacks!

I took some time to read code around that, turned out the tiller namespace is handled by `helm` rather than `helm-diff` when running `helm diff`. It could be resolved entirely in helmfile then.

So, let's add the support for supplying a namespace other than the hard-coded `default` in this issue!
