### ISSUE TITLE
--no-color is not working

### ISSUE THREAD

**Issue by luisdavim** [databus23/helm-diff#98]
I always get a colorful output regardless of passing the `--no-color` flag or not.

**Comment by mumoshu** [comment]
@luisdavim Ah, good catch!

It seems like helm-diff should use [the global variables](https://github.com/mgutz/ansi/blob/9520e82c474b0a04dd04f8a40959027271bab992/ansi.go#L248) instead of string literals of color names, so that ansi.DisableColors takes effect:

https://github.com/databus23/helm-diff/blob/49879b1c62c365d20ebb84a39a362f74fdb921f2/cmd/root.go#L40-L42


That is, I think we should change `"yellow"` like seen in the below example to `ansi.Yellow`:

https://github.com/databus23/helm-diff/blob/05029fe7ee53a4d75c4f15a31ad92de06b16d95d/diff/diff.go#L22

**Comment by vwagner** [comment]
Same problem. We post the helm diff to slack when someone upgrades the cluster. Slack post looks terrible:
<img width="127" alt="screen shot 2018-09-28 at 10 26 13 am" src="https://user-images.githubusercontent.com/2718509/46221021-218fe300-c309-11e8-937d-e5c095835a35.png">

**Comment by databus23** [comment]
The problem is caused by using `PersistentPreRun` multiple times (in parent command and child).
From the spf13/cobra README:

> The Persistent*Run functions will be inherited by children if they do not declare their own. 

Fixing

**Comment by vwagner** [comment]
Thanks @databus23 . I can remove my "fix" now:

`echo $text | sed 's/\.\.\./...|/g'  | sed -e 's/\[0m/|/g' | sed -e 's/\[3.m//g' | tr '|' '\n' `

ugghhhhhh
